### ISSUE TITLE
feed.filter is not working when a design document name is passed

### ISSUE THREAD

**Issue by ceremcem** [cloudant-labs/cloudant-follow#7]
As title says, `feed.filter = "mydesigndoc/myview"` is not working. This error is thrown: 

```
error is:  { Error: Database deleted after change: 483-g1AAAADveJzLYWBgYMlgTmFQSklKzi9KdUhJMjTWy83PzyvOyMxL1UvOyS9NScwr0ctLLckBqmVKZEiy____f1aiD6ouIzN8upIcgGRSPVijOZpGE3wa81iAJEMDkALq3Z-VWIfmVkvCmg9ANANtfpQFAF9RUgE
    at on_feed_response (/home/ceremcem/sync/curr-projects/uhud-pano-mrp/scada.js/lib/dcs/connectors/couch-dcs/node_modules/cloudant-follow/lib/feed.js:271:22)
    at Request.<anonymous> (/home/ceremcem/sync/curr-projects/uhud-pano-mrp/scada.js/lib/dcs/connectors/couch-dcs/node_modules/cloudant-follow/lib/feed.js:234:5)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Request.onRequestResponse (/home/ceremcem/sync/curr-projects/uhud-pano-mrp/scada.js/lib/dcs/connectors/couch-dcs/node_modules/cloudant-follow/node_modules/request/request.js:1074:10)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:563:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:452:20)
  deleted: true,
  last_seq: '483-g1AAAADveJzLYWBgYMlgTmFQSklKzi9KdUhJMjTWy83PzyvOyMxL1UvOyS9NScwr0ctLLckBqmVKZEiy____f1aiD6ouIzN8upIcgGRSPVijOZpGE3wa81iAJEMDkALq3Z-VWIfmVkvCmg9ANANtfpQFAF9RUgE' }
```

If a valid function is passed, it works.

**Comment by ceremcem** [comment]
[Here is](https://github.com/aktos-io/aktos-dcs-node/blob/9785389d845c2bef284553f1a944bea393e10b65/connectors/couch-dcs/couch-nano.ls#L213-L226) my current workaround.

**Comment by smithsz** [comment]
Hey, I'm having some trouble reproducing this. I'm using this example filter from the CouchDB docs:
```json
{
  "_id": "_design/app",
  "filters": {
    "important": "function(doc, req) { if(doc.priority == 'high') { return true; }
    else { return false; }}"
  }
}
```
And instantiating the follow client like so:
```js
var feed = new follow.Feed();
feed.db = 'http://localhost:5984/testdb';
feed.filter = 'app/important';

feed.on('change', function(change) {
  console.log(`got change for doc ${change.id} (seq: ${change.seq})`);
});

feed.on('error', function(er) {
  throw er;
});

feed.follow();
```
Are you able to query the changes feed via `curl` without problems? Something similar to this:
```bash
curl 'http://localhost:5984/testdb/_changes?filter=app/important'
```
I'm wondering if something odd is happening on the server side, i.e. the connection is timing out. Is the filter function quite complex?

Thanks.

**Comment by ceremcem** [comment]
Hmmm... The problem seems that I'm actually [trying to get the changes for a `view`](https://github.com/aktos-io/aktos-dcs-node/blob/9785389d845c2bef284553f1a944bea393e10b65/connectors/couch-dcs/couch-nano.ls#L220), instead of a `filter`.
